
spring:
  thymeleaf:
    cache: false
  datasource:
    url: jdbc:mysql:///1905_demo?serverTimezone=UTC
    username: root
    password: 123
    driver-class-name: com.mysql.jdbc.Driver
server:
  port: 8888